
# This is a template Makefile generated by rpcgen

# Parameters

BIN_DIR = bin

WORKER = $(BIN_DIR)/mr-worker
COORDINATOR = $(BIN_DIR)/mr-coordinator
CLIENT = $(BIN_DIR)/mr-client

SOURCES_WORKER.c = worker/worker.c worker/task_handler.c
SOURCES_WORKER.h = worker/task_handler.h
SOURCES_COORDINATOR.c = coordinator/coordinator.c coordinator/job.c
SOURCES_COORDINATOR.h = coordinator/coordinator.h coordinator/job.h
SOURCES_CLIENT.c = client/client.c
SOURCES_CLIENT.h = 
APPS = wc grep vertex_degree
APPS.c = $(foreach app,$(APPS),app/$(app)/$(app).c)
APPS.h = $(foreach app,$(APPS),app/$(app)/$(app).h)
SOURCES.c = lib/lib.c codec/codec.c app/app.c $(APPS.c)
SOURCES.h = lib/lib.h codec/codec.h app/app.h $(APPS.h)
SOURCES.x = rpc.x

TARGETS_SVC.c = rpc/rpc_svc.c rpc/rpc_xdr.c 
TARGETS_CLNT.c = rpc/rpc_clnt.c rpc/rpc_xdr.c 
TARGETS = rpc/rpc.h rpc/rpc_xdr.c rpc/rpc_clnt.c rpc/rpc_svc.c

OBJECTS_WORKER = $(SOURCES.c:%.c=%.o) $(SOURCES_WORKER.c:%.c=%.o) $(TARGETS_CLNT.c:%.c=%.o)
OBJECTS_COORDINATOR = $(SOURCES.c:%.c=%.o) $(SOURCES_COORDINATOR.c:%.c=%.o) $(TARGETS_SVC.c:%.c=%.o)
OBJECTS_CLIENT = $(SOURCES.c:%.c=%.o) $(SOURCES_CLIENT.c:%.c=%.o) $(TARGETS_CLNT.c:%.c=%.o)
# Compiler flags 

CFLAGS += -g -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include
LDLIBS += -lnsl -lglib-2.0
RPCGENFLAGS =

# Targets 

all : $(WORKER) $(COORDINATOR) $(CLIENT)

$(TARGETS) : rpc/$(SOURCES.x) 
	cd rpc; rpcgen $(RPCGENFLAGS) $(SOURCES.x); \
	rm rpc_svc.c; \
	rpcgen -m -o rpc_svc.c $(RPCGENFLAGS) $(SOURCES.x)

$(OBJECTS_WORKER) : $(SOURCES.c) $(SOURCES.h) $(SOURCES_WORKER.c) $(SOURCES_WORKER.h) $(TARGETS_CLNT.c)

$(OBJECTS_COORDINATOR) : $(SOURCES.c) $(SOURCES.h) $(SOURCES_COORDINATOR.c) $(SOURCES_COORDINATOR.h) $(TARGETS_SVC.c) 

$(OBJECTS_CLIENT) : $(SOURCES.c) $(SOURCES.h) $(SOURCES_CLIENT.c) $(SOURCES_CLIENT.h) $(TARGETS_CLNT.c)

$(BIN_DIR) :
	mkdir -p $(BIN_DIR)

$(WORKER) : $(OBJECTS_WORKER) $(BIN_DIR)
	$(LINK.c) -o $(WORKER) $(OBJECTS_WORKER) $(LDLIBS) 

$(COORDINATOR) : $(OBJECTS_COORDINATOR) $(BIN_DIR)
	$(LINK.c) -o $(COORDINATOR) $(OBJECTS_COORDINATOR) $(LDLIBS)

$(CLIENT) : $(OBJECTS_CLIENT) $(BIN_DIR)
	$(LINK.c) -o $(CLIENT) $(OBJECTS_CLIENT) $(LDLIBS) 

clean:
	$(RM) core $(TARGETS) $(OBJECTS_WORKER) $(OBJECTS_COORDINATOR) $(OBJECTS_CLIENT) $(WORKER) $(COORDINATOR) $(CLIENT)

