# -*- perl -*-
use strict;
use warnings;
use tests::tests;
check_expected (IGNORE_USER_FAULTS => 1, [<<'EOF']);
(create-reuse) begin
(create-reuse) Main started
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: first round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Thread ran: second round
(create-reuse) Main finished
(create-reuse) end
create-reuse: exit(0)
EOF
pass;
